services:
  mysql-server:
    image: mysql:8.0
    container_name: mysql-server
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin --log-bin-trust-function-creators=1
    environment:
      MYSQL_ROOT_PASSWORD: iqlab@2025
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: iqlab@2025
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped

  zabbix-server:
    image: zabbix/zabbix-server-mysql:7.4-alpine-latest
    container_name: zabbix-server
    depends_on:
      - mysql-server
      - zabbix-snmptraps
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: iqlab@2025
      TZ: Asia/Kolkata
    ports:
      - "10051:10051"
    volumes:
      - zabbix-snmptraps-data:/var/lib/zabbix/snmptraps
    restart: unless-stopped

  zabbix-web:
    image: zabbix/zabbix-web-nginx-mysql:7.4-alpine-latest
    container_name: zabbix-web
    depends_on:
      - zabbix-server
      - mysql-server
    environment:
      DB_SERVER_HOST: mysql-server
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: iqlab@2025
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_NAME: "Identiqa NMS"
      PHP_TZ: Asia/Kolkata
    expose:
      - "8080"
    volumes:
      - ./zabbix-custom-ui/favicon.ico:/usr/share/zabbix/favicon.ico
      - ./zabbix-custom-ui/brand.conf.php:/usr/share/zabbix/local/conf/brand.conf.php:ro
      - ./zabbix-custom-ui/rebranding/identiqa.png:/usr/share/zabbix/rebranding/identiqa.png:ro
    restart: unless-stopped

  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-7.4-latest
    container_name: zabbix-agent
    depends_on:
      - zabbix-server
    environment:
      ZBX_SERVER_HOST: zabbix-server
      HOSTNAME: zabbix-agent
    ports:
      - "10050:10050"
    restart: unless-stopped

  zabbix-snmptraps:
    image: zabbix/zabbix-snmptraps:latest
    container_name: zabbix-snmptraps
    ports:
      - "162:162/udp"
    volumes:
      - zabbix-snmptraps-data:/var/lib/zabbix/snmptraps
    restart: unless-stopped

  license-agent:
    build:
      context: ./license-agent
      dockerfile: Dockerfile
    container_name: license-agent
    volumes:
      - ./license/license.lic:/app/license.lic:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  license-proxy:
    build:
      context: ./license-proxy
      dockerfile: Dockerfile
    container_name: license-proxy
    depends_on:
      - zabbix-web
      - license-agent
    ports:
      - "8080:3333"
    volumes:
      - ./license/license.lic:/app/license.lic:ro
      - ./license-proxy/custom.html:/app/custom.html:ro
    restart: unless-stopped

volumes:
  mysql-data:
  zabbix-snmptraps-data:
